export const db = "note-flare"
export const noteCollection = "notes"
export const userCollection = "users"
export const commentCollection = "comments"
export const likeCollection = "like"
export const noteAttachmentBucket = "note-attachments"