export const subjects = [
  { name: 'All Subjects', value: 'all' },
  { name: 'Mathematics', value: 'mathematics' },
  { name: 'Physics', value: 'physics' },
  { name: 'Chemistry', value: 'chemistry' },
  { name: 'Biology', value: 'biology' },
  { name: 'Computer Science', value: 'computer-science' },
  { name: 'English', value: 'English' },
  { name: 'Hindi', value: 'Hindi' },
  { name: 'PHE', value: 'PHE' },
  { name: 'Economics', value: 'Economics' },
  { name: 'History', value: 'History' },
  { name: 'Civics', value: 'Civics' },
  { name: 'Geography', value: 'Geography' },
]